export const cartTypeAction = {
	TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_ITEM: 'REMOVE_ITEM',
	DECREMENT_CART_ITEM: 'DECREMENT_CART_ITEM',
	CLEAR_ALL_CART_ITEMS: 'CLEAR_ALL_CART_ITEMS',
};
